### PR TITLE
Update the cmdlet map for Get-MsolDirSync*

### PR DESCRIPTION
**Pull request by matsimon**
Add mappings for `Get-MsolDirSyncConfiguration` and `Get-MsolDirSyncFeatures`, it seems like this information is now available via `Get-MgDirectoryOnPremiseSynchronization`.

With the clock really ticking on the MSOnline module having to look up CmdLets is really needed, the map is still missing quite some needed data, let's help closing the gaps.

### CODE REVIEW

**Comment by msewaweru** [comment]
@matsimon - thank you for your contribution. We'll review and apply accordingly.
@SteveMutungi254 - please review this.

**Review by SteveMutungi254 — APPROVED** [review]
Approved. Looks good.

**Comment by msewaweru** [comment]
@timayabi2020 - please merge this.

**Comment by msewaweru** [comment]
Changes effect in PR #382

**Comment by matsimon** [comment]
Thanks for the update, glad this Cmdlet map was expanded nonetheless. :-)

**Pull request closed without merging**
