### PR TITLE
Updated the get-started articles as per SDK v2 changes

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by msewaweru** [comment]
@carolkigoonya adding you to the reviewers.

**Review by peombwa — CHANGES_REQUESTED** [review]
Thanks @msewaweru for getting started on this! Please see my suggestions on the PR.

**Comment by CarolKigoonya** [comment]
Thanks @msewaweru the documentation looks good. I only have one comment which I have raised an issue for, we need to mention how customers can get the access token to use for app only and delegated experiences inorder to use Invoke request.  cc @peombwa and @timayabi2020

**Comment by msewaweru** [comment]
@peombwa, I committed your suggestions. Please approve if ok.

**Review by peombwa — APPROVED** [review]

**Pull request merged**
