### PR TITLE
Added content for passwordless authentication

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by msewaweru** [comment]
@f4rty - Requesting for your review on this change. Thanks.

**Comment by f4rty** [comment]
May be remove the first (FIDO) from 'Fast ID Online (FIDO) v2.0 (FIDO2)'. Feels like a pleonasm.

Also, I think we need to emphasise the great usability of Passwordless, too, replacing this 'Passwords are a primary attack vector.'

**Comment by msewaweru** [comment]
@timayabi2020, please merge this.

**Comment by msewaweru** [comment]
@CelesteDG , this is ready for merging. Thanks.

**Pull request merged**
