### PR TITLE
Add codeowners file

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by msewaweru** [comment]
Fixes #290.

**Comment by msewaweru** [comment]
@peombwa - I have added this file as requested. Please review and let me know.
 I see Steve and Carol have no write access. Do you have right to change that?

**Review by peombwa — APPROVED** [review]

**Review by peombwa — APPROVED** [review]
I've added Carol and Steve to the list of maintainers.

**Comment by msewaweru** [comment]
@timayabi2020 - please merge this.

**Pull request merged**
