### PR TITLE
Troubleshooting and error handling article

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by maisarissi** [comment]
Hi @msewaweru . Just saw that this was closed. Does that mean it won't be merged?

**Comment by msewaweru** [comment]
> Hi @msewaweru . Just saw that this was closed. Does that mean it won't be merged?

Hi @maisarissi - I noticed build was not starting for some changes I did so I closed so I could reopen and trigger a build but I can reopen anymore. I don't have the reopen button. Can you reopen from your end?

**Comment by maisarissi** [comment]
I believe I don't have the right permissions as I don't see any reopen button too!
Maybe @CelesteDG can help us?

**Comment by msewaweru** [comment]
I will retry later and possibly get help if it still doesn't work. Thanks.

**Pull request closed without merging**
