### PR TITLE
Added the ms.technology value

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by msewaweru** [comment]
Hi @CelesteDG- Continuing the work to update the medata values for this docset. In this PR, I have updated the ms.technology value. Not sure if the missing ms.technology is the reason for the [build warnings](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202301041106486745-179/BuildReport?accessString=328bfd898f60a4d8bff2b6131c2063b3d9b5da232b3bec12b183540a36b7b5ff) about invalid ms.prod values.

Please review and let me know. Thanks.

**Comment by CelesteDG** [comment]
This looks good, @msewaweru - Based on this we won't need to add ms.technology to every .md file and the default ms.product value is what's indicated in the config file. The ms.product value will then get overridden on an individual basis when we add the values to the individual cmdlet .md files when they get autogenerated.

**Comment by CelesteDG** [comment]
Approving and merging this PR

**Comment by msewaweru** [comment]
Thank you, @CelesteDG. Yes. Timothy has already autogenerated the ms.prod values on the individual cmdlet.md files. Some files as missing this value and I'm trying to investigate why, so we can sort it out once Timothy is back from leave.

**Pull request merged**
